# Generated by Django 3.2.12 on 2022-11-03 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profil_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
