# Generated by Django 3.2.12 on 2022-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221103_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
